# Generated by Django 5.2.5 on 2025-08-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('product_type', models.CharField(choices=[('piece', 'Pièce'), ('moto', 'Moto')], default='piece', max_length=10)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
