# Generated by Django 5.2.5 on 2025-08-14 08:54
from django.db import migrations

def normalize_empty_sku_to_null(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(sku='').update(sku=None)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_sku'),
    ]


    operations = [
        migrations.RunPython(normalize_empty_sku_to_null, reverse_code=migrations.RunPython.noop),
    ]