# Generated by Django 5.2.5 on 2025-08-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_update_sales_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='kind',
            field=models.CharField(choices=[('P', 'Pièce'), ('M', 'Moto')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Espèce'), ('mobile', 'Mobile Money'), ('card', 'Carte')], default='cash', max_length=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], default='draft', max_length=12),
        ),
    ]
