# Generated by Django 5.2.5 on 2025-08-15 15:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_salespointstock_reserved_qty'),
        ('products', '0006_normalize_empty_sku_to_null'),
        ('sales', '0005_sale_kind_alter_sale_customer_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage de validation par la caisse', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage d'annulation", null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(blank=True, help_text='Caissier/ère ayant validé la vente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant reçu du client lors de la validation', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, default='DIVERS', max_length=120),
        ),
        migrations.AlterField(
            model_name='sale',
            name='kind',
            field=models.CharField(choices=[('P', 'Pièces'), ('M', 'Moto')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Espèce'), ('mobile', 'Mobile Money'), ('card', 'Carte')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('awaiting_cashier', 'En attente de caisse'), ('approved', 'Validée par caisse'), ('rejected', 'Rejetée'), ('cancelled', 'Annulée')], default='awaiting_cashier', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['salespoint', 'created_at'], name='sale_sp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sale_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['salespoint', 'status'], name='sale_sp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='saleitem_sale_prod_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('salespoint', 'number'), name='unique_sale_number_per_sp'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='saleitem_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='saleitem_price_gte_0'),
        ),
    ]
