# Generated by Django 5.2.5 on 2025-08-21 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stocktransaction'),
        ('sales', '0006_sale_approved_at_sale_cancelled_at_sale_cashier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='sale_total_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('received_amount__gte', 0), ('received_amount__isnull', True), _connector='OR'), name='sale_received_amount_none_or_gte_0'),
        ),
    ]
