# Generated by Django 5.2.5 on 2025-08-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_sale_total_amount_gte_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_in_words',
            field=models.CharField(blank=True, default='', help_text='Montant en lettres', max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='chassis_number',
            field=models.CharField(blank=True, default='', help_text='N° de châssis (moto)', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_details',
            field=models.JSONField(blank=True, default=dict, help_text='Détails client étendus (nom, téléphones, société, domicile, profession, adresse, demeurant à, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='engine_number',
            field=models.CharField(blank=True, default='', help_text='N° de moteur (moto)', max_length=100),
        ),
    ]
