# Generated by Django 5.2.5 on 2025-08-21 10:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stocktransaction'),
        ('products', '0006_normalize_empty_sku_to_null'),
        ('sales', '0008_sale_amount_in_words_sale_chassis_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Marge brute = total_amount - total_cost', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Somme des coûts des lignes au moment de la vente', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='line_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='line_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Coût unitaire au moment de la vente', max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='sale_total_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('gross_profit__gte', 0), ('gross_profit__lte', 0), _connector='OR'), name='sale_gross_profit_any'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='saleitem_cost_gte_0'),
        ),
    ]
