# Generated by Django 5.2.5 on 2025-08-21 12:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_gross_profit_sale_total_cost_saleitem_line_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.cancellationrequest')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.saleitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cxl_line_qty_gt_0')],
            },
        ),
    ]
