# Generated by Django 5.2.5 on 2025-08-22 15:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_cancellationline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('kind', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'created_at'], name='sales_notif_user_id_ed1f3f_idx'), models.Index(fields=['user', 'read_at'], name='sales_notif_user_id_709dd9_idx')],
            },
        ),
    ]
