# Generated by Django 5.2.5 on 2025-08-13 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0002_salespoint_stock_transfer_delete_tempmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salespoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='inventory.salespoint'),
        ),
    ]
