# Generated by Django 5.2.5 on 2025-08-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_salespoint_stock_transfer_delete_tempmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salespoint',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-created_at']},
        ),
    ]
