# Generated by Django 5.2.5 on 2025-08-13 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_salespoint_options_alter_transfer_options'),
        ('providers', '0002_brand_provider_delete_tempmodel_brand_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespoint',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salespoints', to='providers.brand'),
        ),
        migrations.AddField(
            model_name='salespoint',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
