# Generated by Django 5.2.5 on 2025-08-14 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_salespoint_brand_salespoint_phone'),
        ('products', '0006_normalize_empty_sku_to_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPointStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_qty', models.IntegerField(default=0)),
                ('sold_qty', models.IntegerField(default=0)),
                ('transfer_in', models.IntegerField(default=0)),
                ('transfer_out', models.IntegerField(default=0)),
                ('alert_qty', models.IntegerField(default=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salespoint_stocks', to='products.product')),
                ('salespoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salespoint_stocks', to='inventory.salespoint')),
            ],
            options={
                'ordering': ['product__name'],
                'unique_together': {('salespoint', 'product')},
            },
        ),
    ]
