# Generated by Django 5.2.5 on 2025-08-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_salespointstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespointstock',
            name='reserved_qty',
            field=models.IntegerField(default=0),
        ),
    ]
