# Generated by Django 5.2.5 on 2025-08-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_salespointstock_reserved_qty'),
        ('products', '0006_normalize_empty_sku_to_null'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salespointstock',
            index=models.Index(fields=['salespoint', 'product'], name='inventory_s_salespo_75962d_idx'),
        ),
    ]
