# Generated by Django 5.2.5 on 2025-08-20 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_salespointstock_inventory_s_salespo_75962d_idx'),
        ('products', '0006_normalize_empty_sku_to_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(help_text='Quantité (positive = entrée, négative = sortie)')),
                ('reason', models.CharField(choices=[('sale', 'Vente'), ('return', 'Retour client'), ('transfer_in', 'Transfert entrant'), ('transfer_out', 'Transfert sortant'), ('restock', 'Réapprovisionnement'), ('adjustment', 'Ajustement')], max_length=20)),
                ('reference', models.CharField(blank=True, default='', help_text='Référence externe (numéro de vente, transfert, etc.)', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='products.product')),
                ('salespoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='inventory.salespoint')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['salespoint', 'product', 'created_at'], name='inventory_s_salespo_ae6b13_idx'), models.Index(fields=['reason', 'created_at'], name='inventory_s_reason_8cbc2b_idx')],
            },
        ),
    ]
