# Generated by Django 5.2.5 on 2025-08-21 21:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stocktransaction'),
        ('products', '0006_normalize_empty_sku_to_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('fulfilled', 'Servie'), ('cancelled', 'Annulée')], default='draft', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restock_requests', to=settings.AUTH_USER_MODEL)),
                ('salespoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_requests', to='inventory.salespoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestockLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('remaining_qty', models.IntegerField(default=0)),
                ('alert_qty', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.restockrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='restockrequest',
            index=models.Index(fields=['salespoint', 'status', 'created_at'], name='inventory_r_salespo_7c7e69_idx'),
        ),
        migrations.AddIndex(
            model_name='restockline',
            index=models.Index(fields=['request', 'product'], name='inventory_r_request_e7d1f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='restockline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='restock_qty_gt_0'),
        ),
        migrations.AlterUniqueTogether(
            name='restockline',
            unique_together={('request', 'product')},
        ),
    ]
