# Generated by Django 5.2.5 on 2025-08-21 22:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_transfer_acknowledged_at_transfer_acknowledged_by'),
        ('products', '0006_normalize_empty_sku_to_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('fulfilled', 'Servie'), ('cancelled', 'Annulée')], default='draft', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('from_salespoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_out', to='inventory.salespoint')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('to_salespoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_in', to='inventory.salespoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('available_at_source', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.transferrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['from_salespoint', 'to_salespoint', 'status', 'created_at'], name='inventory_t_from_sa_74819a_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='transfer_req_qty_gt_0'),
        ),
        migrations.AlterUniqueTogether(
            name='transferrequestline',
            unique_together={('request', 'product')},
        ),
    ]
