# Generated by Django 5.2.5 on 2025-08-22 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_transferrequest_transferrequestline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='number_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='number_seq',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['from_salespoint', 'number_date', 'number_seq'], name='inventory_t_from_sa_94c1c0_idx'),
        ),
    ]
