# Generated by Django 5.2.5 on 2025-08-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_transferrequest_number_transferrequest_number_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespoint',
            name='is_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
