# Generated by Django 5.2.5 on 2025-08-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_salespoint_is_warehouse'),
        ('products', '0006_normalize_empty_sku_to_null'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='restockline',
            name='restock_qty_gt_0',
        ),
        migrations.AddField(
            model_name='restockline',
            name='quantity_approved',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity approved by warehouse', null=True),
        ),
        migrations.AddField(
            model_name='restockline',
            name='quantity_requested',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity originally requested', null=True),
        ),
        migrations.AddField(
            model_name='restockline',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='When this line was validated by salespoint', null=True),
        ),
        migrations.AddField(
            model_name='restockrequest',
            name='reference',
            field=models.CharField(blank=True, help_text='Reference number (e.g., WH-DDMMYY-P-0001)', max_length=50),
        ),
        migrations.AddField(
            model_name='restockrequest',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restockline',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Legacy field - use quantity_requested instead'),
        ),
        migrations.AlterField(
            model_name='restockrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('fulfilled', 'Servie'), ('cancelled', 'Annulée'), ('partially_validated', 'Partiellement validé'), ('validated', 'Validé')], default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='restockline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_requested__gt', 0)), name='restock_qty_requested_gt_0'),
        ),
    ]
