# Generated by Django 5.2.5 on 2025-08-24 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_restock_validation_fields'),
        ('products', '0006_normalize_empty_sku_to_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='restockrequest',
            index=models.Index(fields=['status', 'created_at'], name='inventory_r_status_59a989_idx'),
        ),
        migrations.AddIndex(
            model_name='restockrequest',
            index=models.Index(fields=['reference', 'created_at'], name='inventory_r_referen_656081_idx'),
        ),
        migrations.AddIndex(
            model_name='salespointstock',
            index=models.Index(fields=['salespoint', 'alert_qty'], name='inventory_s_salespo_692725_idx'),
        ),
        migrations.AddIndex(
            model_name='salespointstock',
            index=models.Index(fields=['product', 'opening_qty'], name='inventory_s_product_2763fd_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['reference', 'created_at'], name='inventory_s_referen_63e306_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['salespoint', 'reason', 'created_at'], name='inventory_s_salespo_2ace05_idx'),
        ),
    ]
