# Generated by Django 5.2.5 on 2025-08-24 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_performance_indexes'),
        ('products', '0006_normalize_empty_sku_to_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockValidationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('quantity_validated', models.PositiveIntegerField(help_text='Quantity validated by manager')),
                ('stock_before_validation', models.IntegerField(help_text='Stock quantity before validation')),
                ('stock_after_validation', models.IntegerField(help_text='Stock quantity after validation')),
                ('cost_price_at_validation', models.DecimalField(decimal_places=2, help_text='Product cost price at validation time', max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Total value of validated quantity', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('restock_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_audits', to='inventory.restockrequest')),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restock_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Audit de validation d'approvisionnement",
                'verbose_name_plural': "Audits de validation d'approvisionnement",
                'ordering': ['-validated_at'],
                'indexes': [models.Index(fields=['restock_request', 'validated_at'], name='inventory_r_restock_de7bca_idx'), models.Index(fields=['product', 'validated_at'], name='inventory_r_product_f4312e_idx')],
            },
        ),
    ]
