# Generated by Django 5.2.5 on 2025-09-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_stocktransaction_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockline',
            name='stock_qty_at_validation',
            field=models.IntegerField(blank=True, help_text='Salespoint stock quantity at validation time', null=True),
        ),
    ]
