# Generated by Django 5.2.5 on 2025-09-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_transferrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespointstock',
            name='location',
            field=models.CharField(blank=True, default='', help_text="Emplacement dans l'entrepôt", max_length=50),
        ),
    ]
