# Generated by Django 5.2.5 on 2025-09-18 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_salespointstock_location'),
        ('products', '0006_normalize_empty_sku_to_null'),
        ('providers', '0002_brand_provider_delete_tempmodel_brand_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salespointstock',
            name='location',
        ),
        migrations.AddField(
            model_name='restockrequest',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restock_requests', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='restockrequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total purchase amount', max_digits=12),
        ),
        migrations.CreateModel(
            name='RestockRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity to restock')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Purchase cost price', max_digits=12)),
                ('wholesale_price', models.DecimalField(decimal_places=2, help_text='Wholesale price', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost for this item', max_digits=12)),
                ('quantity_validated', models.PositiveIntegerField(blank=True, help_text='Quantity validated by warehouse manager', null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.restockrequest')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restock_item_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product__name'],
                'indexes': [models.Index(fields=['request', 'product'], name='inventory_r_request_c4feff_idx'), models.Index(fields=['validated_at'], name='inventory_r_validat_2ee99e_idx')],
                'unique_together': {('request', 'product')},
            },
        ),
    ]
