# Generated by Django 5.2.5 on 2025-08-16 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_salespointstock_inventory_s_salespo_75962d_idx'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('total_amount', models.PositiveBigIntegerField(help_text='Montant total des ventes (FCFA)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], db_index=True, default='pending', max_length=16)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_reports', to=settings.AUTH_USER_MODEL)),
                ('salespoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_reports', to='inventory.salespoint')),
            ],
            options={
                'verbose_name': 'Rapport de caisse (quotidien)',
                'verbose_name_plural': 'Rapports de caisse (quotidiens)',
                'ordering': ['-report_date', '-created_at'],
                'unique_together': {('cashier', 'salespoint', 'report_date')},
            },
        ),
        migrations.DeleteModel(
            name='TempModel',
        ),
    ]
